name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy code
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.DEPLOY_HOST}}
          username: ${{secrets.DEPLOY_USER}}
          password: ${{secrets.DEPLOY_PASSWORD}}
          script: |
            cd ./visual/visualDocker;

            sudo docker-compose down;

            git pull;
            docker-compose up --build;