name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Docker Compose Services
        run: sudo docker-compose down

      - name: Pull Latest Changes
        run: git pull

      - name: Start Docker Compose Services
        run: sudo docker-compose up --build